# Generated by Django 3.2.22 on 2023-10-25 12:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_de_tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion_de_Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('duracion_estimada', models.FloatField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_finalizacion', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('prioridad', models.IntegerField()),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('PR', 'Progreso'), ('CO', 'Completada')], max_length=2)),
                ('completada', models.BooleanField()),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('hora_vencimiento', models.TimeField(default=django.utils.timezone.now)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tareas.usuario')),
                ('etiquetas_asociadas', models.ManyToManyField(to='gestion_de_tareas.Etiqueta')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tareas.proyecto')),
                ('usuarios_asignados', models.ManyToManyField(related_name='usuarios_asignados', through='gestion_de_tareas.Asignacion_de_tarea', to='gestion_de_tareas.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creador', to='gestion_de_tareas.usuario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='proyectos_asignados',
            field=models.ManyToManyField(to='gestion_de_tareas.Usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tareas.usuario')),
                ('comentario_tarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tareas.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion_de_tarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tareas.tarea'),
        ),
        migrations.AddField(
            model_name='asignacion_de_tarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_de_tareas.usuario'),
        ),
    ]
