# Generated by Django 3.2.22 on 2023-10-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario_tarea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_tarea', to='gestion_de_tareas.tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_tareas', to='gestion_de_tareas.proyecto'),
        ),
    ]
